# Generated by Django 6.0.3 on 2026-03-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
