# Generated by Django 6.0.3 on 2026-03-04 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0002_node_is_ghost'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='node_images/'),
        ),
    ]
