# Generated by Django 6.0.3 on 2026-03-04 23:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0003_node_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('PERSON', 'Person'), ('COMPANY', 'Company'), ('MEETING', 'Meeting')], max_length=10, unique=True)),
                ('default_properties', models.JSONField(blank=True, default=dict)),
                ('default_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
