# Generated by Django 6.0.3 on 2026-03-08 21:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0004_nodetemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('VOICE_NOTE', 'Voice Note'), ('DOCUMENT', 'Document'), ('FREEFORM_NOTE', 'Freeform Note')], max_length=20)),
                ('original_file', models.FileField(blank=True, null=True, upload_to='ingestions/')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('dsl_commands', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBING', 'Transcribing'), ('EXTRACTING', 'Extracting'), ('RESOLVING', 'Resolving'), ('WRITING', 'Writing'), ('SUMMARIZING', 'Summarizing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('failed_step', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ResolutionCandidate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extracted_name', models.CharField(max_length=255)),
                ('extracted_email', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_company', models.CharField(blank=True, default='', max_length=255)),
                ('extracted_title', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('AUTO_LINKED', 'Auto-Linked')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolution_matches', to='network_graph.node')),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_candidates', to='network_graph.ingestion')),
                ('resolved_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_from', to='network_graph.node')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
