# Generated by Django 6.0.3 on 2026-03-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0005_ingestion_node_summary_resolutioncandidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestion',
            name='auto_create',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ingestion',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingestion',
            name='source_type',
            field=models.CharField(choices=[('VOICE_NOTE', 'Voice Note'), ('DOCUMENT', 'Document'), ('FREEFORM_NOTE', 'Freeform Note'), ('MEETING', 'Meeting')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TRANSCRIBING', 'Transcribing'), ('EXTRACTING', 'Extracting'), ('RESOLVING', 'Resolving'), ('WRITING', 'Writing'), ('SUMMARIZING', 'Summarizing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20),
        ),
    ]
