# Generated by Django 6.0.3 on 2026-03-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_graph', '0006_add_ingestion_title_autocreate_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
