# Generated by Django 6.0.3 on 2026-03-10 09:40

from django.db import migrations


def backfill_email(apps, schema_editor):
    """Copy properties['Email'] to the new email field for existing PERSON nodes."""
    Node = apps.get_model("network_graph", "Node")
    for node in Node.objects.filter(node_type="PERSON"):
        if isinstance(node.properties, dict):
            email = str(node.properties.get("Email", "") or "").strip()
            if email:
                node.email = email
                node.save(update_fields=["email"])


class Migration(migrations.Migration):

    dependencies = [
        ("network_graph", "0007_add_node_email_field"),
    ]

    operations = [
        migrations.RunPython(backfill_email, migrations.RunPython.noop),
    ]
